AWSTemplateFormatVersion: '2010-09-09'
Description: 'Secrets'
Parameters:
  DBMasterUsername:
    Description: 'The master user name for the DB instance (ignored when DBSnapshotIdentifier is set, value used from snapshot).'
    Type: 'String'
    Default: master

Resources:
  DatabaseSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub '${AWS::StackName}-db'
      GenerateSecretString:
        SecretStringTemplate: !Sub '{"username": "${DBMasterUsername}"}'
        GenerateStringKey: "password"
        PasswordLength: 30
        ExcludeCharacters: '\/ @&?`"^*~:$%'

Outputs:
  DatabaseSecretArn:
    Description: 'The ARN of the database secret'
    Value: !Ref DatabaseSecret
    Export:
      Name: !Join [ ':', [ !Ref 'AWS::StackName', 'DatabaseSecretArn' ] ]