---
AWSTemplateFormatVersion: "2010-09-09"
Description: VPC service endpoint and NLB to database
Parameters:
  ParentVPCStack:
    Description: 'Stack name of parent VPC stack'
    Type: String
    Default: sohail-alpha-vpc
Resources:
  NlbRdsProxyTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${AWS::StackName}-nlb-tg
      TargetType: ip
      Port: 5432
      Protocol: TCP
      VpcId:
        Fn::ImportValue:
          !Join [':', [!Ref 'ParentVPCStack', 'VPCId']]
      Targets:
      - Id: 10.0.2.114
        Port: 5432
      - Id: 10.0.3.154
        Port: 5432

  NlbRdsProxy:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub ${AWS::StackName}-nlb
      Scheme: internal
      Type: network
      Subnets:
        - Fn::ImportValue:
            !Join [':', [!Ref 'ParentVPCStack', 'PrivateSubnetOne']]
        - Fn::ImportValue:
            !Join [':', [!Ref 'ParentVPCStack', 'PrivateSubnetTwo']]
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-nlb
    DependsOn: NlbRdsProxyTargetGroup
  
  NlbRdsProxyListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn:
      - NlbRdsProxy
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref 'NlbRdsProxyTargetGroup'
          Type: 'forward'
      LoadBalancerArn: !Ref 'NlbRdsProxy'
      Port: 5432
      Protocol: TCP

  VSE:
    Type: 'AWS::EC2::VPCEndpointService'
    Properties:
      AcceptanceRequired: true
      NetworkLoadBalancerArns:
        - !Ref NlbRdsProxy
  VSEPermissions:
    Type: AWS::EC2::VPCEndpointServicePermissions
    Properties:
      ServiceId: !GetAtt VSE.ServiceId
      AllowedPrincipals:
        - !Sub "arn:aws:iam::999999999999:root"
