---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Create a cloudfront dist for website'
Parameters:
  ParentWafStack:
    Type: String
    Default: sohail-app-admin-cdn-waf
  BucketName:
    Type: String
    Description: The name of the S3 bucket that stores the static website files.
    Default: admin.sohail.online
  BucketDomainName:
    Type: String
    Default: admin.sohail.online.s3.eu-west-2.amazonaws.com
  DomainName:
    Type: String
    Description: The domain name of the static website.
    Default: admin.sohail.online
  HostedZoneId:
    Type: String
    Default: "XXX999"
Resources:
  OriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub '${BucketName} - origin access identity'
  
  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: !Sub '${DomainName} => ${BucketDomainName}'
        Enabled: true
        PriceClass: PriceClass_100
        DefaultRootObject: index.html
        Aliases:
          - !Ref DomainName
        Origins:
          - DomainName: !Sub ${BucketDomainName}
            Id: !Sub 'S3-${BucketName}'
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${OriginAccessIdentity}'
        DefaultCacheBehavior:
          AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
          CachedMethods:
            - GET
            - HEAD
          TargetOriginId: !Sub 'S3-${BucketName}'
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: all
          ViewerProtocolPolicy: redirect-to-https
          MinTTL: 0
          DefaultTTL: 0
          MaxTTL: 0
          Compress: true
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        ViewerCertificate:
          AcmCertificateArn: !Ref DomainNameCertificate
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
        Restrictions:
          GeoRestriction:
            RestrictionType: whitelist
            Locations:
              - GB
        WebACLId: 
          Fn::ImportValue:
            !Join [':', [!Ref 'ParentWafStack', 'WafWebAclArn']]

  DomainNameCertificate: 
    Type: "AWS::CertificateManager::Certificate"
    Properties: 
      DomainName: !Ref DomainName
      ValidationMethod: DNS
      DomainValidationOptions:
      - DomainName: !Ref DomainName
        HostedZoneId: !Ref HostedZoneId

  DnsAlias:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref HostedZoneId #admin.sohail.online.
      RecordSets:
      - Name: !Ref DomainName
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2 # aws zone id for cloudfront
          DNSName: !GetAtt Distribution.DomainName
